### ISSUE TITLE
Handle LinearRingTrait

### ISSUE THREAD

**Issue by rafaqz** [evetion/WellKnownGeometry.jl#36]
Currently this isn't implemented

https://github.com/evetion/WellKnownGeometry.jl/blob/a34201e2ccdbf0463e5d4680a13b9b38fab3c306/src/wkt.jl#L23-L31

**Comment by evetion** [comment]
As it's not in the official spec, but people have extended it (similar to our woes in other file formats).

**Comment by rafaqz** [comment]
Ah right. GBIF spec used to say that it supported those but seems its removed them anyway
